
-- Products Table
create table products (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category text,
  image_url text,
  link text,
  features text[], -- Array of strings for feature points
  keywords text[], -- Array of strings for search
  unique(title)
);

-- Services Table
create table services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  image_url text,
  image_url text,
  link text,
  keywords text[],
  unique(title)
);

-- Team Members Table
create table team_members (
  id bigint generated by default as identity primary key,
  name text not null,
  role text,
  message_heading text,
  message_text text,
  image_url text,
  key text unique -- e.g., 'nasir', 'affan' for internal mapping
);

-- Features (Blue Cards) Table
create table features (
  id bigint generated by default as identity primary key,
  key text unique, -- 'readymade', 'experience'
  title text,
  icon_url text,
  description_html text
);
